name: 'Merged to staging'
description: 'Check if the current PR branch is merged to staging'
author: 'GitHub'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'docker'
  image: 'Dockerfile'

